### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by ghost** [apgapg/json_table#1]
As he user scrolls new to the bottom, it makes a http call, returns with the JSON and inserts them.

You want a PR ?

**Comment by AppleEducate** [comment]
I am going to implement this in my dart_tables packages for Flutter. I will support pagination. It will a much nicer API being able to set up the table with json though

**Comment by AppleEducate** [comment]
https://github.com/AppleEducate/plugins/tree/master/packages/data_tables

**Comment by apgapg** [comment]
@AppleEducate This will something cool. Looking forward to it

**Comment by AppleEducate** [comment]
Ill keep you posted, I’ll send some PRs as mine will depend on this 😁

**Comment by apgapg** [comment]
Supported pagination in v1.3.0
