### ISSUE TITLE
When we have nested json data then json converted to String

### ISSUE THREAD

**Issue by shubh-151410** [apgapg/json_table#10]
String getFormattedValue(dynamic value) {
    if (value == null) return column?.defaultValue ?? '';
    if (column?.valueBuilder != null) {
      return column.valueBuilder(value);
    }
    return value.toString();
  }

in Code you have **return value.toString();** 
this cause error but if i am using only **return value** can work perfect for me for nested json please fix this.

**Comment by Kurokirisu** [comment]
I'm having the same issue. I can't use the custom columns either as I don't know how many columns  I need to render when I get the data. Could you please fix this?

**Comment by shubh-151410** [comment]
We need to go in library code and in code one function is present and
return type is String. We need to convert to return String  To return
dynamic

**Comment by apgapg** [comment]
If you dont want to use columns then you must have flat data because value needs to be string when set to Text. 
If i remove .toString thing from value, issue may arrise if value isnt a string
