### ISSUE TITLE
http request sample needed

### ISSUE THREAD

**Issue by singnoi** [apgapg/json_table#11]
Can someone provide me sample of how to get jason from web then display please.

the widget is really useful i will use it in my project but I was tried to show json from the web but it failed, need a good short sample thank you.

**Comment by apgapg** [comment]
https://www.youtube.com/watch?v=9csIbj3o8tw

**Comment by singnoi** [comment]
Many thanks,
really appreciate your hard work.
I know it hard work because i'm dev too.

thank you again

**Comment by singnoi** [comment]
I can follow the youtube demo through, and this change my learning curve because I used to struggle there for long
