### ISSUE TITLE
importing local json file to use in json table widget

### ISSUE THREAD

**Issue by sambitraze** [apgapg/json_table#14]
i am getting an issue: 'Future<dynamic>' is not a subtyoe of  type  'List<Dynamic>

code :

```
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:json_table/json_table.dart';

class SewingHourlyProduction extends StatefulWidget {
  @override
  _SewingHourlyProductionState createState() => _SewingHourlyProductionState();
}
class _SewingHourlyProductionState extends State<SewingHourlyProduction> {
  Future<dynamic> loadValue () async {    
    String jsonData = await DefaultAssetBundle.of(context).loadString("assets/HPR.json"); 
    final jsonResult = jsonDecode(jsonData);
    print(jsonResult);
    return jsonResult;
  }
  @override
  Widget build(BuildContext context) {
    dynamic json = loadValue();
    return Scaffold(
      appBar: AppBar(title: Text('Hourly Production Report')),
      body: Container(
      child: Column(
        children: <Widget>[
          JsonTable(
            json,
            showColumnToggle: true,
            tableHeaderBuilder: (String header) {
                      return Container(
                        padding: EdgeInsets.symmetric(
                            horizontal: 8.0, vertical: 4.0),
                        decoration: BoxDecoration(
                            border: Border.all(width: 0.5),
                            color: Colors.grey[300]),
                        child: Text(
                          header,
                          textAlign: TextAlign.center,
                          style: Theme.of(context).textTheme.display1.copyWith(
                              fontWeight: FontWeight.w700,
                              fontSize: 14.0,
                              color: Colors.black87),
                        ),
                      );
                    },
                    tableCellBuilder: (value) {
                      return Container(
                        padding: EdgeInsets.symmetric(
                            horizontal: 4.0, vertical: 2.0),
                        decoration: BoxDecoration(
                            border: Border.all(
                                width: 0.5,
                                color: Colors.grey.withOpacity(0.5))),
                        child: Text(
                          value,
                          textAlign: TextAlign.center,
                          style: Theme.of(context).textTheme.display1.copyWith(
                              fontSize: 14.0, color: Colors.grey[900]),
                        ),
                      );
                    },
                    allowRowHighlight: true,
                    rowHighlightColor: Colors.yellow[500].withOpacity(0.7),
                    paginationRowCount: 4,
          )
        ],
      ),
      ),
    );
  }
}






```

**Comment by apgapg** [comment]
Hey You cant use future in build method for JsonTable
You have to create a new method for loading data and then setstate that jsondata to make table work properly

**Comment by apgapg** [comment]
call load value in init state and call setstate when you get your list of data.
Add a null check in build method so as to show loading before data is set

**Comment by sambitraze** [comment]
now i am able to import and decode and print the json data but upon  using it in json_table() 
thanks for support till now :)

i am getting this error: 

type
'_InternalLinkedHashMap<String,dynamic>' is not a subtype of type 'List<dynamic>'


code:


import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:json_table/json_table.dart';

class SewingHourlyProduction extends StatefulWidget {
  @override
  _SewingHourlyProductionState createState() => _SewingHourlyProductionState();
}
class _SewingHourlyProductionState extends State<SewingHourlyProduction> {
  @override
  void initState() {
    loadVaue();
    super.initState();
  }
  dynamic response;
  void loadVaue() async{
    await DefaultAssetBundle.of(context).loadString("assets/HPR.json").then((s) {
      setState(() {
        response = json.decode(s);
        print(response);
      });
    });
  }
  
  
  @override
  Widget build(BuildContext context) {   
    return Scaffold(
      appBar: AppBar(title: Text('Hourly Production Report')),
      body: Container(
        child: Column(
          children: <Widget>[
            JsonTable(response),
             FlatButton(onPressed: (){loadVaue();}, child: Text('hel')),
          ],
        )
      ),
    );
  }
}
