### ISSUE TITLE
RangeError (index): Invalid value: Only valid value is 0: 4

### ISSUE THREAD

**Issue by dukenebur** [apgapg/json_table#30]
Hi guys! How are you?

The component is great and works perfect. But i'm having trouble now:

I am showing a json on the screen and when wanting with a button to load another of smaller size, this error appears:

**_RangeError (index): Invalid value: Only valid value is 0: 4
The relevant error-causing widget was
    JsonTable_** 

But if with the button I load another one of greater size the problem does not happen

Could you help me please?

**Comment by apgapg** [comment]
@dukenebur  Can you share some sample code? or data which you are passing into table?

**Comment by dukenebur** [comment]
Hi! How are you! Thanks for your quickly response! I have already solved this!

Kind Regards
