### ISSUE TITLE
I can't able to load json data from url

### ISSUE THREAD

**Issue by MPVIRANIDEVELOPER** [apgapg/json_table#5]
can you please help me to load data from api request i tried many but i can't able to load data from dynamic data please help me waiting for your fast response...

**Comment by apgapg** [comment]
Please show me the code sample

**Comment by MPVIRANIDEVELOPER** [comment]
i have done implementation as separate code

**Comment by apgapg** [comment]
But without code sample i can't solve your problem

**Comment by MPVIRANIDEVELOPER** [comment]
I have solved the problem thank you very much fot your response

**Comment by alexlovar** [comment]
hi, i have the same problem to load the json data.
this is my code
`
......
Future getData2() async{
  var url = 'https://ss.com/tablaht.php?nit=123456&maquina=Consultorio';
  http.Response response = await http.get(url);
  var data = jsonDecode(response.body);
  return data;
}

class _SimpleTableState extends State<SimpleTable> {
  bool toggle = false;
  var _result ;
  
  void initState() {
    Timer.periodic(Duration(seconds: 15), (timer) {
      getData2().then((result) {
        setState(() {
          _result = result;
        });
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    if (_result == null) {
      _result = jsonDecode('[{"Fecha":"0000-00-00 ","Hora":"00:00:00","Temperatura":"0.0","Humedad":"0.0"}]');
      print('resultado null');
    }

     var json =_result;
     print(json.toString());

    return Scaffold(
      body: Container(
        padding: EdgeInsets.all(16.0),
        child: toggle
            ? Column(
          children: [
            JsonTable(
              json,........
`

print(json.toString()); give me this:
[{Fecha: 2019-09-04 , Hora: 23:24:32, Temperatura: 32.4, Humedad: 49.3}, {Fecha: 2019-09-04 , Hora: 23:23:59, Temperatura: 32.3, Humedad: 49.2},.........
 but after this point i get the follow error:
I/flutter (19120): Another exception was thrown: type 'List<dynamic>' is not a subtype of type 'String'
 could you please help me , thanks!

**Comment by MPVIRANIDEVELOPER** [comment]
I have implemented directly to my code and than i can load json data from
stful widget

MP VIRANI OFFICIAL

**Comment by apgapg** [comment]
@alexlovar The data provided to JsonTable must be a List of map. In your case its a string thats why it throws typecast exception
